(->> (range)
     (map #(* % %))
     (take 13)
     (reduce +)
     (printf "First 13 square pyramidal numbers: %d (https://oeis.org/A000330)\n"))

(->> (range)
     (map #(* % %))
     (filter even?)
     (take 13)
     (reduce +)
     (printf "Sum of the first 13 even squares: %d (https://oeis.org/A002492)\n"))
